name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r .requirements.txt --pre

    - name: Build jsonschema
      run: |
        cd schema
        make all

    - name: Validate jsonschemas are valid
      run: |
        for schema_f in schema/vrs/json/*; do
          python -c "import json, jsonschema; jsonschema.Draft202012Validator.check_schema(json.load(open('$schema_f')))"
        done

    - name: Build HTML
      run: |
        SPHINXOPTS='-W --keep-going' make html
