name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r .requirements.txt --pre

      - name: Test with pytest
        run: |
          pytest tests/
